name: test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  macos:
    name: Test on macOS
    runs-on: macos-latest
    steps:
    - uses: swift-actions/setup-swift@v2
    - uses: actions/checkout@v4
    - name: Build and test
      run: |
        swift test --skip ExtendSchemaTests
