name: test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  macos:
    name: Test on macOS
    runs-on: macos-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - uses: actions/checkout@v4
    - name: Build and test
      run: |
        swift test --filter ExtendSchemaTests --filter SubscriptionTests
